# Generated by Django 4.2.23 on 2025-06-15 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reparto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("elettronica", "Elettronica"),
                            ("bellezza", "Bellezza"),
                            ("libri", "Libri"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Reparto",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"groups__name": "Office Managers"},
                        related_name="reparti_ufficio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Office Managers assegnati",
                    ),
                ),
            ],
            options={"verbose_name": "Reparto", "verbose_name_plural": "Reparti",},
        ),
    ]
