# Generated by Django 4.2.21 on 2025-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerce", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
